---
name: ci

on:
  push:
    branches:
      - master-2.2.224
    tags-ignore:
      - "*"
  pull_request:
    branches:
      - master-2.2.224
  workflow_dispatch: {}
  schedule:
    - cron: 0 18 * * *

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    # uncomment after testing
    #uses: openrewrite/gh-automation/.github/workflows/ci-maven.yml@main
    uses: ci-maven.yml
